/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserDestinataireDTO } from './userDestinataireDTO';
import { WorkflowPreset } from './workflowPreset';


export interface StepPreset { 
    id?: number;
    title?: string;
    level?: number;
    description?: string;
    workflowPreset?: WorkflowPreset;
    destinataires?: Array<UserDestinataireDTO>;
    actions?: Array<StepPreset.ActionsEnum>;
}
export namespace StepPreset {
    export type ActionsEnum = 'CREATE' | 'UPDATE' | 'DELETE';
    export const ActionsEnum = {
        CREATE: 'CREATE' as ActionsEnum,
        UPDATE: 'UPDATE' as ActionsEnum,
        DELETE: 'DELETE' as ActionsEnum
    };
}