/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DocumentDto } from '../Document.model';
import { Commentaire } from './commentaire';
import { StepPreset } from './stepPreset';
import { Workflow } from './workflow';

export interface Step { 
    id?: number;
    stepPreset?: StepPreset;
    status?: Step.StatusEnum;
    documents?: Array<DocumentDto>;
    documentsActions?: Array<DocumentDto>;
    workflow?: Workflow;
    discussions?: Array<Commentaire>;
}
export namespace Step {
    export type StatusEnum = 'WAITING' | 'IN_PROGRESS'| 'REJECTED' | 'DONE' | 'Annulled';
    export const StatusEnum = {
        WAITING: 'WAITING' as StatusEnum,
        INPROGRESS: 'IN_PROGRESS' as StatusEnum,
        REJECTED: 'REJECTED' as StatusEnum,
        DONE: 'DONE' as StatusEnum,
        Annulled: 'Annulled' as StatusEnum
    };
}