/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UtilisateurDto } from '../Utilisateur.model';
import { BaseDto } from 'app/zynerator/dto/BaseDto.model';

/**
 * User destinataire to be created
 */
export interface UserDestinataireDTO extends BaseDto{

    utilisateur: UtilisateurDto;
    poids: number;
    stepId: number;
    shouldSign: boolean;
}
